---
- name: Ensure that the systemd package is installed
  tags: systemd
  become: true
  yum:
    name: systemd
    state: present
  register: systemd_yum

- block:
    - name: Executing systemd control tasks
      import_tasks: systemd_control.yml

    - name: Executing systemd service tasks
      import_tasks: systemd_service.yml

    - name: Executing systemd rc.local tasks
      import_tasks: systemd_rc_local.yml
      when: systemd_rc_local|length > 0
  tags: systemd
  become: true
  when: systemd_yum|success
...
