---
- name: Ensure that the systemd package is installed
  tags: systemd
  become: true
  yum:
    name: systemd
    state: present
  register: systemd_yum

- name: Attempting to import systemd related tasks
  block:
    - import_tasks: systemd_ctl.yml
    - import_tasks: systemd_rcl.yml
    - import_tasks: systemd_svc.yml
  when: systemd_yum is success
...
