---
- name: Attempting to apply systemd hostnamectl configurations
  tags: systemd
  become: true
  command: |
    /usr/bin/hostnamectl "set-{{ item.key|replace('_', '-') }}" "{{ item.value }}"
  with_dict: "{{ systemd_hostnamectl }}"
  when:
    - item.key is defined
    - item.value is defined

- name: Attempting to apply systemd localectl configurations
  tags: systemd
  become: true
  command: |
    /usr/bin/localectl "set-{{ item.key|replace('_', '-') }}" "{{ item.value }}"
  with_dict: "{{ systemd_localectl }}"
  when:
    - item.key is defined
    - item.value is defined

- name: Attempting to apply systemd timedatectl configurations
  tags: systemd
  become: true
  command: |
    /usr/bin/timedatectl "set-{{ item.key|replace('_', '-') }}" "{{ item.value }}"
  with_dict: "{{ systemd_timedatectl }}"
  when:
    - item.key is defined
    - item.value is defined
...
