---
- name: Attempting to overlay rc.local configurations and permissions
  tags: systemd
  become: true
  lineinfile:
    path: /etc/rc.d/rc.local
    line: "{{ item }}"
    owner: root
    group: root
    mode: 0750
    state: present
  with_items: "{{ systemd_rc_local }}"
...
